# This workflow will build a docker image and publish it to dockerhub

name: CI/CD

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set output variables
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Check output variables
        run: |
          echo ${{ steps.vars.outputs.tag }}

      - name: build :hack
        # Non-Master push without a release
        if: github.event.action != 'published' && github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: |
            bernedom/yoctobuilder:hack

      - name: build and push develop to DockerHub
        # Master push without a release
        if: github.event.action != 'published' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            bernedom/yoctobuilder:develop

      - name: build and push latest to DockerHub
        # Master push for release
        if: github.event.action == 'published'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            bernedom/yoctobuilder:latest
            bernedom/yoctobuilder:${{ steps.vars.outputs.tag }}
